dist: focal
language: python

matrix:
    include:
        - python: '2.7'
          dist: bionic
          env:

        - python: '3.6'
          env:
            - COVERAGE="true"
            - DILL="true"

        - python: '3.7'
          env:

        - python: '3.8'
          env:

        - python: '3.9'
          env:

        - python: '3.10'
          env:

        - python: '3.11-dev'
          env:
            - PYVERSION="3.11"

        - python: 'pypy2.7-7.3.1' # most recent
          dist: xenial
          env:
            - PYPY_VERSION="2.7"

        - python: 'pypy3.6-7.3.3' # most recent
          dist: bionic
          env:
            - PYPY_VERSION="3.6"

        - python: 'pypy3.7-7.3.5' # most recent
          dist: bionic
          env:
            - PYPY_VERSION="3.7"

    allow_failures:
        - python: '2.7'
        - python: 'pypy2.7-7.3.1'
        - python: '3.11-dev'
    fast_finish: true

cache:
    pip: true

before_install:
    - set -e  # fail on any error
    - if [[ $COVERAGE == "true" ]]; then pip install coverage; fi
    - if [[ $DILL == "true" ]]; then pip install dill; fi

install:
    - python setup.py build && python setup.py install

script:
    - if [[ $PYVERSION != "3.11" ]]; then PYVERSION=$TRAVIS_PYTHON_VERSION ; fi
    - if [[ $PYVERSION == "pypy2.7-7.3.1" ]]; then PYVERSION=py$PYPY_VERSION ; fi
    - if [[ $PYVERSION == "pypy3.6-7.3.3" ]]; then PYVERSION=py$PYPY_VERSION ; fi
    - if [[ $PYVERSION == "pypy3.7-7.3.5" ]]; then PYVERSION=py$PYPY_VERSION ; fi
    - cd py$PYVERSION
    - cp ../.coveragerc .coveragerc
    - for test in multiprocess/tests/__init__.py; do echo $test ; if [[ $COVERAGE == "true" ]]; then coverage run -a $test > /dev/null; else python $test > /dev/null; fi ; done
    - if [[ $PYVERSION == *"py3"* ]]; then for test in multiprocess/tests/test_multiprocessing_fork.py; do echo $test ; if [[ $COVERAGE == "true" ]]; then coverage run -a $test > /dev/null; else python $test > /dev/null; fi ; done ; else for test in multiprocess/tests/*.py; do if [[ $test != *"__"* && $test != *"mp_"* ]]; then echo $test ; if [[ $COVERAGE == "true" ]]; then coverage run -a $test > /dev/null; else python $test > /dev/null; fi ; fi; done ; fi
    - if [[ $COVERAGE == "true" ]]; then cat .coverage; else echo ''; fi
    - if [[ $COVERAGE == "true" ]]; then mv .coverage ../.coverage; else echo ''; fi
    - cd ..

after_success:
    - if [[ $COVERAGE == "true" ]]; then bash <(curl -s https://codecov.io/bash); else echo ''; fi
